services:
  db:
    image: postgres:11.2
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:7.0-alpine'
    ports:
      - '127.0.0.1:6379:6379'
    command: redis-server
    restart: unless-stopped
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
